### PR TITLE
Topic Branch "Private_migrate_hint" to show ping pong activity between nodelets

### PR DESCRIPTION
**Pull request by kaushikvelusamy**
Cleaned up the code to show that there is a ping pong activity between the nodelets when "cilk_migrate_hint" and "cilk_spawn" is used in the class private member function. 

To be compared with the PR "main_migrate_hint" https://github.com/wohlbier/4.01_repl/pull/3

### CODE REVIEW

**Comment by wohlbier** [comment]
You are deleting large sections of the example so it is very hard to know what you are trying to show. This example is meant to show creation of two matrix classes using the replicated base class and population of a vector on specific nodelets, and to observe the expected migration pattern.

I had convinced myself that the migration pattern is as expected and I explained it in main.cc. It seems that you are suggesting that there are too many migrations because of the cilk calls in the constructor. Let's figure out how to most clearly highlight this. This might mean making a new example, as suggested below.

I’m sorry about the names 4.01_, 4.1_, etc. I know they are confusing. Each one is meant to convey a specific concept and the numbers kind of came up as I realized that I was making incorrect assumptions and had to rewind to an earlier number. If the concept you want to convey is not clearly demonstrated in any one example, then consider making your own new example using the same infrastructure that I can fork and work on.

**Comment by kaushikvelusamy** [comment]
Maybe I misunderstood this. Let me make one last attempt. 

Directly running your program 4.1_repl_class without any modifications, I see the below pattern. Is this an expected behavior? You can just check for the words marked in Bold.

First 20 lines from short trace.

Simulation @0 s with local date and time= Wed Apr 24 11:20:35 2019

TID 0 NLET 0 SPAWN CHILDTID 1 FUNC _ZN8Matrix_tC2El @cycle 38584
TID 0 **NLET 0 MIGRATE DEST 1** FUNC _ZN8Matrix_tC2El @cycle 42263 TPC 0x8000365b Inst LD8A
TID 0 NLET 1 SPAWN CHILDTID 2 FUNC _ZN8Matrix_tC2El @cycle 42533
TID 0 **NLET 1 MIGRATE DEST 0** FUNC _ZN8Matrix_tC2El @cycle 42644 TPC 0x8000371d Inst LDE
TID 0 **NLET 0 MIGRATE DEST 2** FUNC _ZN8Matrix_tC2El @cycle 46348 TPC 0x8000365b Inst LD8A
TID 0 NLET 2 SPAWN CHILDTID 3 FUNC _ZN8Matrix_tC2El @cycle 46616
TID 0 **NLET 2 MIGRATE DEST 0** FUNC _ZN8Matrix_tC2El @cycle 46727 TPC 0x8000371d Inst LDE
TID 1 NLET 0 DIED NLET 0 FUNC _ZN8Matrix_tC2El @cycle 48432
TID 0 **NLET 0 MIGRATE DEST 3** FUNC _ZN8Matrix_tC2El @cycle 50342 TPC 0x8000365b Inst LD8A
TID 0 NLET 3 SPAWN CHILDTID 4 FUNC _ZN8Matrix_tC2El @cycle 50613
TID 0 **NLET 3 MIGRATE DEST 0** FUNC _ZN8Matrix_tC2El @cycle 50724 TPC 0x8000371d Inst LDE
TID 2 NLET 1 MIGRATE DEST 0 FUNC _ZN8Matrix_tC2El @cycle 54658 TPC 0x800036d5 Inst LDE
TID 0 **NLET 0 MIGRATE DEST 4** FUNC _ZN8Matrix_tC2El @cycle 54848 TPC 0x8000365b Inst LD8A
TID 0 NLET 4 SPAWN CHILDTID 5 FUNC _ZN8Matrix_tC2El @cycle 55116
TID 0 **NLET 4 MIGRATE DEST 0** FUNC _ZN8Matrix_tC2El @cycle 55227 TPC 0x8000371d Inst LDE
TID 2 NLET 0 DIED NLET 0 FUNC _ZN8Matrix_tC2El @cycle 57406
TID 3 NLET 2 MIGRATE DEST 0 FUNC _ZN8Matrix_tC2El @cycle 58741 TPC 0x800036d5 Inst LDE
TID 0 **NLET 0 MIGRATE DEST 5** FUNC _ZN8Matrix_tC2El @cycle 59335 TPC 0x8000365b Inst LD8A
TID 0 NLET 5 SPAWN CHILDTID 6 FUNC _ZN8Matrix_tC2El @cycle 59606
TID 0 **NLET 5 MIGRATE DEST 0** FUNC _ZN8Matrix_tC2El @cycle 59717 TPC 0x8000371d Inst LDE

**Comment by wohlbier** [comment]
Great! Let's discuss!

I would claim that that migration pattern is what is expected. Of course if you can improve it that would be super!

See if this makes sense:
- main runs on TID 0 on nodelet 0, it calls the constructor on matrix A
- within the constructor cilk migrate and spawn is called 16 times, one for each row, with a sync once in the constructor

For each row:
- migrate_hint migrates TID 0 to the respective nodelet where the new thread is spawned with TID N
- TID 0 returns to nodelet 0 after spawning
- The spawned thread TID N migrates to nodelet 0 after it is done

It does this for A and B. I think if you look at the pattern you pasted above you will confirm this. You could comment out the code below the allocation of A and B to confirm.

What's not clear to me at the moment is the migrations from 2=>5 and 5=>2 mentioned on lines 167 and 168. I just pushed an update to the repo noting that these migrations require explanation.

Please let me know what you think about all of this.

**Comment by wohlbier** [comment]
Kaushik, this repository
https://github.com/wohlbier/4.05_repl_constructor
is more like the example that you were suggesting. I left the loop in instead of using 2 and 5, and I see the ping pong. Please see if you can fix it. Maybe go back to using 2 and 5 and see if you can get it ultimately to use the loop.

I'm going to close this PR.

**Pull request closed without merging**
